# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-10-01 17:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_system', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='username',
            field=models.CharField(max_length=200, verbose_name='昵称（真实姓名）'),
        ),
    ]
