# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-09-10 12:18
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('submission_system', '0003_auto_20161030_0342'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, null=True, verbose_name='评论详细')),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='submission_system.HomeworkAnswer', verbose_name='所属答案')),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='讲师')),
            ],
            options={
                'verbose_name': '讲师评论',
                'verbose_name_plural': '讲师评论',
            },
        ),
    ]
